Turned runc into a bashly script

diff --git a/.local/bin/runc b/.local/bin/runc
--- a/.local/bin/runc
+++ b/.local/bin/runc
@@ -1,26 +1,207 @@
-#!/bin/bash -eu
+#!/usr/bin/env bash
+# This script was generated by bashly (https://github.com/DannyBen/bashly)
+# Modifying it manually is not recommended
 
-TEMP_FILE="$(mktemp)"
-TEMP_EXECUTABLE="$(mktemp)"
+# :script.bash3_bouncer
+if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
+  printf "bash version 4 or higher is required\n"
+  exit 1
+fi
 
-finish() {
-	rm -f "$TEMP_FILE"
-	rm -f "$TEMP_EXECUTABLE"
+# :command.root_command
+root_command() {
+  # :src/root_command.sh
+  #!/bin/bash -eu
+
+  TEMP_FILE="$(mktemp)"
+  TEMP_EXECUTABLE="$(mktemp)"
+
+  finish() {
+  	rm -f "$TEMP_FILE"
+  	rm -f "$TEMP_EXECUTABLE"
+  }
+
+  trap finish EXIT
+
+  CODE="$(cat)"
+
+  generate_c_program "$CODE" > "$TEMP_FILE"
+
+  gcc -xc "$TEMP_FILE" -o "$TEMP_EXECUTABLE"
+
+  "$TEMP_EXECUTABLE"
 }
 
-trap finish EXIT
+# :command.version_command
+version_command() {
+  echo "$version"
+}
 
-cat <<-EOF > "$TEMP_FILE"
-	#include <stdio.h>
-	#include <stdlib.h>
+# :command.usage
+runc_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "runc - Quickly compile and run a C program\n"
+    echo
 
-	int main(int argc, char *argv[])
-	{
-		$(cat)
-	}
-	EOF
+  else
+    printf "runc - Quickly compile and run a C program\n"
+    echo
 
-gcc -xc "$TEMP_FILE" -o "$TEMP_EXECUTABLE"
+  fi
 
-"$TEMP_EXECUTABLE"
+  printf "Usage:\n"
+  printf "  runc\n"
+  printf "  runc --help | -h\n"
+  printf "  runc --version | -v\n"
+  echo
 
+  if [[ -n $long_usage ]]; then
+    printf "Options:\n"
+    # :command.usage_fixed_flags
+    echo "  --help, -h"
+    printf "    Show this help\n"
+    echo
+    echo "  --version, -v"
+    printf "    Show version number\n"
+    echo
+
+    # :command.usage_examples
+    printf "Examples:\n"
+
+    printf "  runc <<EOF\n    printf(\"Hello world!\n\");\n  EOF\n"
+    echo
+
+  fi
+}
+
+# :command.normalize_input
+normalize_input() {
+  local arg flags
+
+  while [[ $# -gt 0 ]]; do
+    arg="$1"
+    if [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
+      input+=("${BASH_REMATCH[1]}")
+      input+=("${BASH_REMATCH[2]}")
+    elif [[ $arg =~ ^(-[a-zA-Z0-9])=(.+)$ ]]; then
+      input+=("${BASH_REMATCH[1]}")
+      input+=("${BASH_REMATCH[2]}")
+    elif [[ $arg =~ ^-([a-zA-Z0-9][a-zA-Z0-9]+)$ ]]; then
+      flags="${BASH_REMATCH[1]}"
+      for (( i=0 ; i < ${#flags} ; i++ )); do
+        input+=("-${flags:i:1}")
+      done
+    else
+      input+=("$arg")
+    fi
+
+    shift
+  done
+}
+# :command.inspect_args
+inspect_args() {
+  readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
+  if (( ${#args[@]} )); then
+    echo args:
+    for k in "${sorted_keys[@]}"; do echo "- \${args[$k]} = ${args[$k]}"; done
+  else
+    echo args: none
+  fi
+
+  if (( ${#other_args[@]} )); then
+    echo
+    echo other_args:
+    echo "- \${other_args[*]} = ${other_args[*]}"
+    for i in "${!other_args[@]}"; do
+      echo "- \${other_args[$i]} = ${other_args[$i]}"
+    done
+  fi
+}
+
+# :command.user_lib
+# :src/lib/sample_function.sh
+#!/bin/bash
+generate_c_program() {
+  local code="${1?No code}"
+  cat <<-EOF
+    #include <stdio.h>
+    #include <stdlib.h>
+
+    int main(int argc, char *argv[])
+    {
+      $code
+    }
+EOF
+}
+
+# :command.command_functions
+
+# :command.parse_requirements
+parse_requirements() {
+  # :command.fixed_flag_filter
+  case "${1:-}" in
+  --version | -v )
+    version_command
+    exit
+    ;;
+
+  --help | -h )
+    long_usage=yes
+    runc_usage
+    exit
+    ;;
+
+  esac
+  # :command.environment_variables_filter
+  # :command.dependencies_filter
+  # :command.command_filter
+  action="root"
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+    -* )
+      printf "invalid option: %s\n" "$key"
+      exit 1
+      ;;
+
+    * )
+      # :command.parse_requirements_case
+      printf "invalid argument: %s\n" "$key"
+      exit 1
+      ;;
+
+    esac
+  done
+  # :command.required_args_filter
+  # :command.required_flags_filter
+  # :command.catch_all_filter
+  # :command.default_assignments
+  # :command.whitelist_filter
+}
+
+# :command.initialize
+initialize() {
+  version="0.0.1"
+  long_usage=''
+  set -euo pipefail
+
+  # :src/initialize.sh
+}
+
+# :command.run
+run() {
+  declare -A args=()
+  declare -a other_args=()
+  declare -a input=()
+  normalize_input "$@"
+  parse_requirements "${input[@]}"
+
+  if [[ $action == "root" ]]; then
+    root_command
+  fi
+}
+
+initialize
+run "$@"
